FROM openjdk:17-alpine
MAINTAINER Matt Fichman <matt.fichman@gmail.com>
WORKDIR /minecraft

COPY /images/minecraft /minecraft

EXPOSE 25565

RUN ln -sf /minecraft/data/mods /minecraft/mods
RUN ln -sf /minecraft/data/minecraft_server.jar /minecraft/minecraft_server.jar
RUN ln -sf /minecraft/data/modder.jar /minecraft/modder.jar
RUN ln -sf /minecraft/data/server.properties /minecraft/server.properties

CMD sh /minecraft/boot.sh
