release:
  environment:
  - RAILS_ENV=development
  volumes:
  - ./volumes/postgres:/bundle/volumes/postgres

postgres:
  environment:
  - RAILS_ENV=development
  - POSTGRES_HOST_AUTH_METHOD=trust
  volumes:
  - ./volumes/postgres:/var/lib/postgresql/data
  ports:
  - "5432:5432"

web:
  environment:
  - RAILS_ENV=development
  - SSL_PORT=3001

worker:
  environment:
  - RAILS_ENV=development
  volumes:
  - ./volumes/minecraft:/minecraft/data
  - ./volumes/wireguard:/etc/wireguard

logger:
  environment:
  - RAILS_ENV=development

minecraft:
  volumes:
  - ./volumes/minecraft:/minecraft/data

wireguard:
  volumes:
  - ./volumes/wireguard:/etc/wireguard

redis:
  ports:
  - "6379:6379"
