release:
  environment:
  - RAILS_ENV=development
  volumes:
  - ./volumes/postgres:/bundle/volumes/postgres

web:
  environment:
  - RAILS_ENV=development
  volumes:
  - ./config/master.key:/bundle/config/master.key
  ports:
  - "3001:3001"
  - "3000:3000"

worker:
  environment:
  - RAILS_ENV=development
  volumes:
  - ./config/master.key:/bundle/config/master.key
  - ./volumes/minecraft:/minecraft/data
  - ./volumes/wireguard:/etc/wireguard

logger:
  environment:
  - RAILS_ENV=development
  volumes:
  - ./config/master.key:/bundle/config/master.key

minecraft:
  volumes:
  - ./volumes/minecraft:/minecraft/data

wireguard:
  volumes:
  - ./volumes/wireguard:/etc/wireguard

postgres:
  environment:
  - POSTGRES_HOST_AUTH_METHOD=trust
  volumes:
  - postgres:/var/lib/postgresql/data
  ports:
  - "5432:5432"

redis:
  ports:
  - "6379:6379"
