release:
  image: mfichman/minecraft:release
  container_name: release
  command: bin/rails db:migrate

web:
  image: mfichman/minecraft:web
  container_name: web
  restart: always
  environment:
  - SERVER_NAME=${SERVER_NAME}
  - REDIS_URL=redis://redis:6379
  - RAILS_LOG_TO_STDOUT=true
  - SSL_PORT=443
  links:
  - redis
  ports:
  - "80:80"
  - "443:443"

worker:
  image: mfichman/minecraft:worker
  container_name: worker
  restart: always
  environment:
  - REDIS_URL=redis://redis:6379
  links:
  - redis
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  - /volumes/minecraft:/minecraft/data
  - /volumes/wireguard:/etc/wireguard

logger:
  image: mfichman/minecraft:logger
  container_name: logger
  restart: always
  links:
  - redis
  environment:
  - REDIS_URL=redis://redis:6379
  - SERVER_NAME=${SERVER_NAME}
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock

redis:
  image: redis:alpine
  container_name: redis
  restart: always

postgres:
  image: postgres:alpine
  container_name: postgres
  restart: always

minecraft:
  image: mfichman/minecraft
  container_name: minecraft
  stdin_open: true
  tty: true
  restart: always
  volumes:
  - /volumes/minecraft:/minecraft/data
  ports:
  - "25565:25565"

wireguard:
  image: mfichman/minecraft:wireguard
  container_name: wireguard
  restart: always
  stdin_open: true
  tty: true
  net: host
  privileged: true
  volumes:
  - /volumes/wireguard:/etc/wireguard
  - /lib/modules:/lib/modules
  - /usr/src:/usr/src
