# This file contains local-dev overrides. The actual service definitions
# are in services/*.yml
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    volumes:
    - ./volumes/postgres:/var/lib/postgresql/data
    environment:
    - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
    - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
    - "6379:6379"

  release:
    image: mfichman/minecraft:release
    container_name: minecraft-release
    env_file: .env

  web:
    image: mfichman/minecraft:web
    container_name: minecraft-web
    restart: always
    env_file: .env
    ports:
    - "3000:3000"

  worker:
    image: mfichman/minecraft:worker
    container_name: minecraft-worker
    env_file: .env
    extra_hosts:
    - redis:127.0.0.1
    - postgres:127.0.0.1
    - minecraft:127.0.0.1
    volumes:
    - ./volumes/minecraft:/minecraft/data
    - ./volumes/wireguard:/etc/wireguard

  logger:
    container_name: minecraft-logger

  monitor:
    container_name: minecraft-monitor
    env_file: .env
    extra_hosts:
    - redis:127.0.0.1
    - postgres:127.0.0.1
    - minecraft:127.0.0.1

  minecraft:
    volumes:
    - ./volumes/minecraft:/minecraft/data
