release:
  environment:
  - RAILS_ENV=development
  volumes:
  - ./volumes/db:/bundle/volumes/db

web:
  environment:
  - RAILS_ENV=development
  volumes:
  - ./volumes/db:/bundle/volumes/db

worker:
  environment:
  - RAILS_ENV=development
  volumes:
  - ./volumes/db:/bundle/volumes/db
  - ./volumes/minecraft:/minecraft/data
  - ./volumes/wireguard:/etc/wireguard

logger:
  environment:
  - RAILS_ENV=development
  volumes:
  - ./volumes/db:/bundle/volumes/db

minecraft:
  volumes:
  - ./volumes/minecraft:/minecraft/data

wireguard:
  volumes:
  - ./volumes/wireguard:/etc/wireguard

redis:
  ports:
  - "6379:6379"
