version: '3'

services:
  wireguard:
    image: mfichman/wireguard
    #volumes:
      #    - wireguard:/etc/wireguard
    stdin_open: true
    tty: true
    network_mode: host
    privileged: true
    environment:
      - LISTEN_PORT=51820
    ports:
      - "51820:51820"

  web:
    image: mfichman/minecraft:bundle
    command: bin/puma -C config/puma.rb --bind tcp://0.0.0.0:80 --pidfile puma.pid
    restart: always
    environment:
    - REDIS_URL=redis://redis:6379
    - RAILS_LOG_TO_STDOUT=true
    depends_on:
    - redis
    volumes:
    - db:/bundle/db
    ports:
    - "80:80"
    - "443:443"

  worker:
    image: mfichman/minecraft:bundle
    command: bin/sidekiq --queue minecraft.mfichman.net --queue default --concurrency 1
    restart: always
    environment:
    - REDIS_URL=redis://redis:6379
    depends_on:
    - redis
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - db:/bundle/db
    - data:/minecraft/data

  logger:
    image: mfichman/minecraft:bundle
    command: bin/rails minecraft:logs
    restart: always
    environment:
    - REDIS_URL=redis://redis:6379
    - SERVER_NAME=minecraft.mfichman.net
    depends_on:
    - redis
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - db:/bundle/db

  minecraft:
    image: mfichman/minecraft
    container_name: minecraft
    stdin_open: true
    tty: true
    restart: always
    volumes:
    - data:/minecraft/data
    ports:
    - "25565:25565"

  redis:
    image: redis
    restart: always

volumes:
  wireguard:
  db:
  data:

#docker-machine create --driver digitalocean --digitalocean-size s-2vcpu-2gb --digitalocean-access-token $DOTOKEN machine-name


