db:
  image: mfichman/minecraft:bundle
  container_name: db
  command: bin/rails db:migrate
  volumes:
  - /volumes/db:/bundle/volumes/db

web:
  image: mfichman/minecraft:bundle
  container_name: web
  command: bin/rails web
  restart: always
  environment:
  - SERVER_NAME=standbox.mfichman.net
  - REDIS_URL=redis://redis:6379
  - RAILS_LOG_TO_STDOUT=true
  volumes:
  - /volumes/db:/bundle/volumes/db
  links:
  - redis
  ports:
  - "80:80"
  - "443:443"

worker:
  image: mfichman/minecraft:bundle
  container_name: worker
  command: bin/sidekiq --queue ${SERVER_NAME} --queue default --concurrency 1
  restart: always
  environment:
  - REDIS_URL=redis://redis:6379
  links:
  - redis
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  - /volumes/db:/bundle/volumes/db
  - /volumes/minecraft:/minecraft/data
  - /volumes/wireguard:/etc/wireguard

logger:
  image: mfichman/minecraft:bundle
  container_name: logger
  command: bin/rails minecraft:logger
  restart: always
  links:
  - redis
  environment:
  - REDIS_URL=redis://redis:6379
  - SERVER_NAME=${SERVER_NAME}
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  - /volumes/db:/bundle/volumes/db

redis:
  image: redis:alpine
  container_name: redis
  restart: always

minecraft:
  image: mfichman/minecraft
  container_name: minecraft
  stdin_open: true
  tty: true
  restart: always
  volumes:
  - /volumes/minecraft:/minecraft/data
  ports:
  - "25565:25565"

wireguard:
  image: mfichman/minecraft:wireguard
  container_name: wireguard
  restart: always
  stdin_open: true
  tty: true
  net: host
  privileged: true
  volumes:
  - /volumes/wireguard:/etc/wireguard
  - /lib/modules:/lib/modules
  - /usr/src:/usr/src
