# Base system dependencies -------------------------------------------------------------------------
FROM alpine:3.14 as base
MAINTAINER Matt Fichman <matt.fichman@gmail.com>
WORKDIR /bundle

ENV RAILS_ENV=production
ENV RAILS_SERVE_STATIC_FILES=true
ENV BUNDLE_PATH=/bundle/vendor/bundle
ENV BUNDLE_WITHOUT=test:development
ENV BUNDLE_SILENCE_ROOT_WARNING=true

RUN apk add ruby-full postgresql libxml2 libxslt libstdc++ openssl curl
RUN gem install bundler:2.2.27

# Ruby bundle --------------------------------------------------------------------------------------
FROM base as builder

RUN apk add ruby-dev postgresql-dev libxml2-dev libxslt-dev nodejs-dev yarn build-base openssl-dev python2-dev

COPY Gemfile Gemfile.lock /bundle/
RUN bundle install

COPY package.json yarn.lock /bundle/
RUN yarn install --production=true

COPY . /bundle
RUN SECRET_KEY_BASE=`ruby bin/rails secret` ruby bin/rails webpacker:compile

# Production bundle --------------------------------------------------------------------------------
FROM base as bundle
COPY --from=builder /bundle /bundle
RUN mkdir -p /bundle/volumes/{db,minecraft,wireguard}
CMD sh

# Web ----------------------------------------------------------------------------------------------
FROM bundle as web
EXPOSE 80 443
CMD ruby bin/rails web

# Worker -------------------------------------------------------------------------------------------
FROM bundle as worker
CMD ruby bin/rails worker

# Logger -------------------------------------------------------------------------------------------
FROM bundle as logger
CMD ruby bin/rails minecraft:logger

# Release ------------------------------------------------------------------------------------------
FROM bundle as release
CMD ruby bin/rails db:prepare
