version: '2'
services:
  release:
    image: mfichman/minecraft:release
    environment:
    - DATABASE_URL=${DATABASE_URL}
    - RAILS_ENV=development
    - REDIS_URL=${REDIS_URL}
    volumes:
    - ./volumes/postgres:/bundle/volumes/postgres

  web:
    image: mfichman/minecraft:web
    restart: always
    environment:
    - DATABASE_URL=${DATABASE_URL}
    - RAILS_LOG_TO_STDOUT=true
    - RAILS_ENV=development
    - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    - REDIS_URL=${REDIS_URL}
    - SERVER_NAME=${SERVER_NAME}
    - SSL_PORT=443
    ports:
    - "3001:3001"
    - "3000:3000"

  postgres:
    image: postgres:alpine
    restart: always
    volumes:
    - ./volumes/postgres:/var/lib/postgresql/data
    environment:
    - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
    - "5432:5432"

  redis:
    image: redis:alpine
    restart: always
    ports:
    - "6379:6379"

  worker:
    environment:
    - RAILS_ENV=development
    volumes:
    - ./volumes/minecraft:/minecraft/data
    - ./volumes/wireguard:/etc/wireguard

  logger:
    environment:
    - RAILS_ENV=development

  minecraft:
    volumes:
    - ./volumes/minecraft:/minecraft/data

  wireguard:
    volumes:
    - ./volumes/wireguard:/etc/wireguard
