FROM openjdk:17-alpine
MAINTAINER Matt Fichman <matt.fichman@gmail.com>
WORKDIR /minecraft

ENV MINECRAFT_SERVER_JAR_URL=https://launcher.mojang.com/v1/objects/3cf24a8694aca6267883b17d934efacc5e44440d/server.jar
ENV MINECRAFT_SERVER_JAR_VERSION=1.18

COPY /images/minecraft /minecraft

VOLUME /minecraft/data
VOLUME /minecraft/jars

EXPOSE 25565

RUN apk add bash curl

CMD bash /minecraft/boot.sh
