# This file contains local-dev overrides. The actual service definitions
# are in services/*.yml
services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    volumes:
    - ./volumes/postgres:/var/lib/postgresql/data
    environment:
    - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
    - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
    - "6379:6379"

  release:
    image: mfichman/minecraft:release
    container_name: release
    environment:
    - DATABASE_URL
    - RAILS_MASTER_KEY
    - REDIS_URL
    - SERVER_NAME

  web:
    image: mfichman/minecraft:web
    container_name: web
    restart: always
    environment:
    - DATABASE_URL
    - RAILS_MASTER_KEY
    - REDIS_URL
    - SERVER_NAME
    ports:
    - "3000:3000"

  worker:
    image: mfichman/minecraft:worker
    volumes:
    - ./volumes/minecraft:/minecraft/data
    - ./volumes/wireguard:/etc/wireguard

  minecraft:
    volumes:
    - ./volumes/minecraft:/minecraft/data
