version: '3.9'
services:
  boot:
    image: mfichman/minecraft:boot
    network_mode: service:wireguard
    cap_add:
    - CAP_NET_ADMIN
    environment:
    - DATABASE_URL
    - RAILS_MASTER_KEY
    - REDIS_URL
    - SERVER_NAME
