version: '3.9'
services:
  logger:
    image: mfichman/minecraft:logger
    restart: always
    environment:
    - DATABASE_URL
    - RAILS_MASTER_KEY
    - REDIS_URL
    - SERVER_NAME
    # FIXME: Remove this dependency by reading from log file instead?
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
