version: '2'
services:
  logger:
    image: mfichman/minecraft:logger
    container_name: logger
    restart: always
    environment:
    - DATABASE_URL=${DATABASE_URL}
    - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    - REDIS_URL=${REDIS_URL}
    - SERVER_NAME=${SERVER_NAME}
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
