version: '3.9'
services:
  monitor:
    image: mfichman/minecraft:monitor
    container_name: monitor
    restart: always
    network_mode: service:wireguard
    environment:
    - DATABASE_URL
    - RAILS_MASTER_KEY
    - REDIS_URL
    - SERVER_NAME
