version: '3.9'
services:
  monitor:
    image: mfichman/minecraft:monitor
    container_name: monitor
    restart: always
    network_mode: host
    environment:
    - DATABASE_URL=${DATABASE_URL}
    - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    - REDIS_URL=${REDIS_URL}
    - SERVER_NAME=${SERVER_NAME}
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /proc:/proc
