version: '3.9'
services:
  wireguard:
    image: mfichman/minecraft:wireguard
    container_name: wireguard
    network_mode: host
    privileged: true
    restart: always
    volumes:
    - /volumes/wireguard:/etc/wireguard
    - /lib/modules:/lib/modules
    - /usr/src:/usr/src
