version: '3.9'
services:
  worker:
    image: mfichman/minecraft:worker
    restart: always
    network_mode: service:wireguard
    cap_add:
    - CAP_NET_ADMIN
    environment:
    - DATABASE_URL
    - RAILS_MASTER_KEY
    - REDIS_URL
    - SERVER_NAME
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /volumes/minecraft:/minecraft/data
