version: '3.9'
services:
  worker:
    image: mfichman/minecraft:worker
    container_name: worker
    restart: always
    environment:
    - DATABASE_URL=${DATABASE_URL}
    - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    - REDIS_URL=${REDIS_URL}
    - SERVER_NAME=${SERVER_NAME}
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /volumes/minecraft:/minecraft/data
    - /volumes/wireguard:/etc/wireguard
